cluster_name: devops-rke2-demo
provider: gcp         # gcp | aws | local | azure
project_id: devops-workspace-469715
region: us-central1
ssh_key_path: ~/.ssh/id_ed25519.pub

master:
  count: 1
  instance_type: e2-medium

worker:
  count: 2
  instance_type: e2-small

rke2:
  version: v1.30.0
  token: devops-intern-token
