---
- name: Install Jenkins Master + Nginx Reverse Proxy (HTTP)
  hosts: lab3a-ansible-jenkins
  become: yes

  vars:
    jenkins_http_port: 8080
    jenkins_url: "http://{{ ansible_host }}/"

  tasks:
    - name: Install dependencies
      apt:
        name:
          - openjdk-17-jdk
          - curl
        state: present
        update_cache: yes

    - name: Add Jenkins key
      ansible.builtin.get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        dest: /usr/share/keyrings/jenkins-keyring.asc
        mode: '0644'

    - name: Add Jenkins repository
      copy:
        dest: /etc/apt/sources.list.d/jenkins.list
        content: |
          deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Configure Jenkins to listen on all interfaces
      lineinfile:
        path: /etc/default/jenkins
        regexp: '^JENKINS_ARGS='
        line: 'JENKINS_ARGS="--webroot=/var/cache/jenkins/war --httpPort={{ jenkins_http_port }} --httpListenAddress=0.0.0.0"'

    - name: Restart Jenkins
      systemd:
        name: jenkins
        state: restarted
        enabled: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Remove default nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Create Jenkins Reverse Proxy config
      copy:
        dest: /etc/nginx/sites-available/jenkins
        content: |
          server {
              listen 80 default_server;
              server_name _;

              location / {
                  proxy_pass http://127.0.0.1:8080;

                  proxy_set_header Host $host;          
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto http;

                  proxy_redirect off;
              }
          }
        mode: '0644'

    - name: Enable Jenkins Nginx site
      file:
        src: /etc/nginx/sites-available/jenkins
        dest: /etc/nginx/sites-enabled/jenkins
        state: link
        force: yes

    - name: Reload Nginx
      systemd:
        name: nginx
        state: restarted

    - name: Set Jenkins root URL (must match IP)
      copy:
        dest: /var/lib/jenkins/jenkins.model.JenkinsLocationConfiguration.xml
        content: |
          <?xml version='1.1' encoding='UTF-8'?>
          <jenkins.model.JenkinsLocationConfiguration>
            <adminAddress>admin@local</adminAddress>
            <jenkinsUrl>{{ jenkins_url }}</jenkinsUrl>
          </jenkins.model.JenkinsLocationConfiguration>
        owner: jenkins
        group: jenkins
        mode: '0644'

    - name: Restart Jenkins to apply new URL
      systemd:
        name: jenkins
        state: restarted

    - name: Wait for Jenkins password
      wait_for:
        path: /var/lib/jenkins/secrets/initialAdminPassword
        timeout: 30

    - name: Read Jenkins initial admin password
      slurp:
        src: /var/lib/jenkins/secrets/initialAdminPassword
      register: adminpass

    - name: Show Jenkins Initial Password
      debug:
        msg: "Initial Admin Password: {{ adminpass.content | b64decode }}"
